"use client";
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";

const nav = ["Overview","Miners","Logs","Diagnostics","Settings"];
type ManagerStatus={appVersion:string;profile:string;node:{endpoint:string;reachable:boolean;latency_ms:number;error:string|null};bridge:{managed:boolean;state:string;uptime_seconds:number;api_url:string;api:{reachable:boolean;error:string|null;status?:{kaspad_version?:string}}};checked_at:string};
type BridgeWorker={instance?:string;worker?:string;workerName?:string;name?:string;hashrate?:number;hashrateGhs?:number;shares?:number;acceptedShares?:number;status?:string};
type BridgeStats={activeWorkers?:number;totalShares?:number;networkHashrate?:number;bridgeUptime?:number;workers?:BridgeWorker[]};
type BridgeSettings={preset:"automatic"|"iceriver"|"custom";stratumPort:number;variableDifficulty:boolean;sharesPerMinute:number;powerOfTwoClamp:boolean;extranonceSize:number;minimumShareDifficulty:number};
type SettingsModel={settings:BridgeSettings;presets:{automatic:BridgeSettings&{label:string};iceriver:BridgeSettings&{label:string}};protected:{nodeConnection:string;credentialsStored:boolean}};
type SettingsIssue={field:string;message:string};
const formatHashrate=(value?:number)=>value?value>=1e18?`${(value/1e18).toFixed(2)} EH/s`:value>=1e12?`${(value/1e12).toFixed(2)} TH/s`:`${(value/1e9).toFixed(2)} GH/s`:"—";
const workerHashrateGhs=(worker:BridgeWorker)=>worker.hashrateGhs??worker.hashrate??0;
const formatWorkerHashrate=(worker:BridgeWorker)=>formatHashrate(workerHashrateGhs(worker)*1e9);

export default function Home(){
 const [section,setSection]=useState("Overview"); const [manager,setManager]=useState<ManagerStatus|null>(null); const [stats,setStats]=useState<BridgeStats|null>(null); const [hashrateHistory,setHashrateHistory]=useState<number[]>([]); const [error,setError]=useState("");
 const [settingsModel,setSettingsModel]=useState<SettingsModel|null>(null); const [settings,setSettings]=useState<BridgeSettings|null>(null); const [settingsLoading,setSettingsLoading]=useState(false); const [settingsSaving,setSettingsSaving]=useState(false); const [settingsNotice,setSettingsNotice]=useState<{kind:"success"|"error"|"rollback";text:string}|null>(null); const [settingsIssues,setSettingsIssues]=useState<SettingsIssue[]>([]);
 const managerBase=process.env.NEXT_PUBLIC_MANAGER_URL??"";
 const refresh=useCallback(async()=>{try{const statusResponse=await fetch(`${managerBase}/api/manager/status`,{cache:"no-store"});if(!statusResponse.ok)throw new Error(`Manager returned ${statusResponse.status}`);const status=await statusResponse.json();setManager(status);setError("");if(status.bridge.api.reachable){const statsResponse=await fetch(`${managerBase}/api/manager/stats`,{cache:"no-store"});if(statsResponse.ok){const liveStats:BridgeStats=await statsResponse.json();setStats(liveStats);const liveWorkers=Array.isArray(liveStats.workers)?liveStats.workers:[];const combinedGhs=liveWorkers.reduce((total,worker)=>total+workerHashrateGhs(worker),0);setHashrateHistory(previous=>[...previous.slice(-119),combinedGhs*1e9])}else setStats(null)}else setStats(null)}catch(reason){setStats(null);setError(reason instanceof Error?reason.message:"Manager unavailable")}},[managerBase]);
 useEffect(()=>{const initial=window.setTimeout(refresh,0);const timer=window.setInterval(refresh,5000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh]);
 const loadSettings=useCallback(async()=>{setSettingsLoading(true);try{const response=await fetch(`${managerBase}/api/manager/settings`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Settings are unavailable");setSettingsModel(body);setSettings(body.settings);setSettingsIssues([]);setSettingsNotice(null)}catch(reason){setSettingsNotice({kind:"error",text:reason instanceof Error?reason.message:"Settings are unavailable"})}finally{setSettingsLoading(false)}},[managerBase]);
 const choosePreset=(preset:"automatic"|"iceriver"|"custom")=>{if(!settingsModel||!settings)return;if(preset==="custom")setSettings({...settings,preset});else{const selected=settingsModel.presets[preset];setSettings({preset,stratumPort:selected.stratumPort,variableDifficulty:selected.variableDifficulty,sharesPerMinute:selected.sharesPerMinute,powerOfTwoClamp:selected.powerOfTwoClamp,extranonceSize:selected.extranonceSize,minimumShareDifficulty:selected.minimumShareDifficulty})}setSettingsIssues([]);setSettingsNotice(null)};
 const changeSetting=<K extends keyof BridgeSettings>(key:K,value:BridgeSettings[K])=>setSettings(current=>current?{...current,[key]:value,...(key==="preset"?{}:{preset:"custom" as const})}:current);
 const saveSettings=async()=>{if(!settings)return;setSettingsSaving(true);setSettingsIssues([]);setSettingsNotice(null);try{const response=await fetch(`${managerBase}/api/manager/settings`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const body=await response.json();if(!response.ok){if(Array.isArray(body.issues))setSettingsIssues(body.issues);if(body.result==="rolled_back")setSettingsNotice({kind:"rollback",text:body.rollback?.healthy?"Those settings did not start safely. The previous working settings were restored and the bridge is healthy again.":"The previous settings were restored, but the bridge still needs attention."});else setSettingsNotice({kind:"error",text:body.error||"Settings could not be saved."});return}setSettings(body.settings);setSettingsNotice({kind:"success",text:"Settings saved. The bridge restarted and passed its health check."});await refresh()}catch(reason){setSettingsNotice({kind:"error",text:reason instanceof Error?reason.message:"Settings could not be saved."})}finally{setSettingsSaving(false)}};
 const control=async(action:"start"|"stop"|"restart")=>{try{const response=await fetch(`${managerBase}/api/manager/bridge/${action}`,{method:"POST"});if(!response.ok)throw new Error((await response.json()).error||`Action failed (${response.status})`);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Action failed")}};
 const running=manager?.bridge.state==="running"||manager?.bridge.api.reachable===true;
 const hasLiveStats=manager?.bridge.api.reachable===true&&stats!==null;
 const workers=hasLiveStats&&Array.isArray(stats.workers)?stats.workers:[];
 const visibleWorkers=workers.slice(0,5);
 const combinedMinerHashrate=workers.reduce((total,worker)=>total+workerHashrateGhs(worker),0)*1e9;
 const connectedMinerCount=hasLiveStats?(stats.activeWorkers??workers.length):0;
 const history=hasLiveStats?hashrateHistory:[];
 const historyMax=Math.max(1,...history);
 const metricSource=hasLiveStats?"Live bridge API":"Waiting for bridge";
 const metrics=[["Connected miners",hasLiveStats?(stats.activeWorkers??workers.length).toString():"—",metricSource],["Miner hashrate",hasLiveStats?formatHashrate(combinedMinerHashrate):"—",metricSource],["Accepted shares",hasLiveStats?stats.totalShares?.toLocaleString()??"0":"—",metricSource],["Node latency",manager?.node.reachable?`${manager.node.latency_ms} ms`:"—",manager?.node.endpoint??"Not checked"]];
 const healthSummary=manager?.node.reachable?(manager.bridge.api.reachable?"Healthy":"Ready for bridge"):"Attention";
 const stratumHost=useSyncExternalStore(()=>()=>{},()=>window.location.hostname,()=>"your-umbrel-host");
 return <main className="shell">
  <aside><div className="brand">
   {/* SVG stays crisp at every Umbrel display density. */}
   {/* eslint-disable-next-line @next/next/no-img-element */}
   <img src="/kaspa-logo.svg" alt="Kaspa"/><small>Stratum Manager</small></div>
   <nav>{nav.map(x=><button key={x} className={x===section?"active":""} onClick={()=>{setSection(x);if(x==="Settings"&&!settingsModel)void loadSettings()}}>{x}</button>)}</nav>
   <div className="aside-status"><div className="aside-connection"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Rusty Kaspad connected":"Rusty Kaspad unavailable"}</div><dl><div><dt>Node version</dt><dd>{manager?.bridge.api.status?.kaspad_version??"Checking…"}</dd></div><div><dt>App version</dt><dd>{manager?.appVersion??"Checking…"}</dd></div></dl></div>
  </aside>
  <section className="workspace"><header><div><p>LOCAL MINING CONTROL</p><h1>{section}</h1></div><span className="node"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Node reachable":"Checking node"} <b>{manager?.node.latency_ms??"—"} ms</b></span></header>
  {error&&<div className="alert"><strong>Development connection:</strong> {error}. Start the manager on this computer to connect the dashboard.</div>}
  {section==="Overview"?<>
   <section className="hero"><div className="hero-copy"><span className={running?"running":"stopped"}>{running?"● Bridge running":"○ Bridge stopped"}</span><h2>{running?"Mining gateway is online":"Mining gateway is offline"}</h2><p>{running?"Your miners can connect to your own Kaspa node.":"Start the bridge before connecting miners."} <small>{manager?.profile==="umbrel"?"Running locally inside Umbrel.":"Windows development profile connected across your LAN."}</small></p><div className="endpoint"><small>Miner connection address</small><code>{`stratum+tcp://${stratumHost}:5555`}</code></div></div><div className="control"><div className="ring"><b>{running?new Date((manager?.bridge.uptime_seconds??stats?.bridgeUptime??0)*1000).toISOString().slice(11,19):"—"}</b><small>UPTIME</small></div><div className="control-actions"><button disabled={!manager?.bridge.managed||!running} onClick={()=>control("stop")}>Stop</button><button disabled={!manager?.bridge.managed} className="restart" onClick={()=>control(running?"restart":"start")}>{running?"Restart":"Start"}</button></div></div></section>
   <section className="metrics">{metrics.map((m,i)=><article key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={i===0||i===2?"good":""}>{m[2]}</small></article>)}</section>
   <section className="grid"><article className="panel"><div className="panel-head"><div><h3>Miner hashrate</h3><p>Combined live performance</p></div><button disabled>Live session</button></div>{history.length>1?<div className="chart live-chart" aria-label="Live miner hashrate history"><div className="history-points">{history.map((value,index)=><i key={index} style={{height:`${Math.max(4,value/historyMax*100)}%`}} title={formatHashrate(value)}/>)}</div></div>:<div className="chart-empty"><b>Collecting live readings</b><span>The chart appears after two bridge updates.</span></div>}</article>
   <article className="panel system-health"><div className="panel-head"><div><h3>System health</h3><p>Live management checks</p></div><em>{healthSummary}</em></div>{[["Rusty Kaspad RPC",manager?.node.endpoint??"Checking",manager?.node.reachable?"Active":"Unavailable",manager?.node.reachable],["Bridge API",manager?.bridge.api_url??"Checking",manager?.bridge.api.reachable?"Active":"Stopped",manager?.bridge.api.reachable],["Bridge supervisor",manager?.bridge.managed?"Managed":"Disabled in Windows profile",manager?.bridge.managed?"Active":"Expected",Boolean(manager)],["Runtime profile",manager?.profile??"Checking",manager?"Active":"Unavailable",Boolean(manager)]].map(x=><div className="health" key={String(x[0])}><i className={x[3]?"":"bad"}/><strong>{x[0]}<small>{x[1]}</small></strong><span className={x[2]==="Expected"?"safe":""}>{x[2]}</span></div>)}</article></section>
   <section className="panel miners"><div className="panel-head"><div><h3>Active miners</h3><p>Workers currently connected through the Stratum bridge</p></div><button onClick={()=>setSection("Miners")}>View all →</button></div>{visibleWorkers.length?<div className="table"><table><thead><tr><th>Worker</th><th>Instance</th><th>Hashrate</th><th>Accepted shares</th><th>Status</th></tr></thead><tbody>{visibleWorkers.map((worker,index)=>{const name=worker.worker??worker.workerName??worker.name??`Worker ${index+1}`;const status=worker.status??"Unknown";return <tr key={`${name}-${index}`}><td>{name}</td><td>{worker.instance??"—"}</td><td>{formatWorkerHashrate(worker)}</td><td>{(worker.acceptedShares??worker.shares??0).toLocaleString()}</td><td className={status.toLowerCase()}>{status}</td></tr>})}</tbody></table></div>:<div className="miners-empty"><b>No live miner data</b><span>{running?"Miner details will appear when a worker connects.":"Start the bridge to begin monitoring workers."}</span></div>}<div className="miners-foot"><span>Showing up to 5 miners</span>{workers.length>5&&<button onClick={()=>setSection("Miners")}>{workers.length-5} more miner{workers.length-5===1?"":"s"} →</button>}</div></section>
  </>:section==="Miners"?<section className="miners-page">
   <section className={`miners-live-strip ${hasLiveStats?"live":"waiting"}`}><div><i/><span><strong>{hasLiveStats?`${connectedMinerCount} miner${connectedMinerCount===1?"":"s"} connected`:running?"Waiting for miners":"Mining bridge is stopped"}</strong><small>{hasLiveStats?"Live data refreshes every 5 seconds.":running?"Connected workers will appear here automatically.":"Start the bridge from Overview before connecting a miner."}</small></span></div><button onClick={refresh}>Refresh now</button></section>
   <section className="miners-summary"><article><span>Connected miners</span><strong>{hasLiveStats?connectedMinerCount:"—"}</strong><small>{hasLiveStats?"Reporting to the bridge":"Waiting for bridge"}</small></article><article><span>Combined hashrate</span><strong>{hasLiveStats?formatHashrate(combinedMinerHashrate):"—"}</strong><small>Current live performance</small></article><article><span>Accepted shares</span><strong>{hasLiveStats?(stats.totalShares??0).toLocaleString():"—"}</strong><small>Current bridge session</small></article></section>
   <section className="miners-connection"><div><span>MINER CONNECTION ADDRESS</span><h2>Connect miners to your Umbrel</h2><p>Enter this address as the pool URL in each miner. Give every miner a unique worker name so it is easy to identify below.</p></div><code>{`stratum+tcp://${stratumHost}:5555`}</code></section>
   <section className="panel miners-directory"><div className="panel-head"><div><h3>Miner directory</h3><p>Complete live worker list from the Stratum bridge</p></div><span className="directory-count">{hasLiveStats?`${workers.length} shown`:"Not connected"}</span></div>{workers.length?<div className="table"><table><thead><tr><th>Worker</th><th>Instance</th><th>Hashrate</th><th>Accepted shares</th><th>Status</th></tr></thead><tbody>{workers.map((worker,index)=>{const name=worker.worker??worker.workerName??worker.name??`Worker ${index+1}`;const status=worker.status??"Unknown";const statusClass=status.toLowerCase()==="online"?"online":status.toLowerCase()==="idle"?"idle":"";return <tr key={`${name}-${index}`}><td data-label="Worker"><strong>{name}</strong></td><td data-label="Instance">{worker.instance??"—"}</td><td data-label="Hashrate">{formatWorkerHashrate(worker)}</td><td data-label="Accepted shares">{(worker.acceptedShares??worker.shares??0).toLocaleString()}</td><td data-label="Status"><span className={`miner-status ${statusClass}`}><i/>{status}</span></td></tr>})}</tbody></table></div>:<div className="miners-directory-empty"><b>{running?"No miners connected yet":"Bridge is offline"}</b><span>{running?"Check the connection address in your miner, then allow up to a minute for its first reading.":"Return to Overview and start the mining bridge."}</span>{!running&&<button className="restart" onClick={()=>setSection("Overview")}>Go to Overview</button>}</div>}<div className="miners-directory-foot"><span>Worker names and statistics come directly from the local bridge.</span><span>{manager?.checked_at?`Last checked ${new Date(manager.checked_at).toLocaleTimeString()}`:"Waiting for first check"}</span></div></section>
  </section>:section==="Diagnostics"?<section className="panel diagnostics"><div className="panel-head"><div><h3>Connection diagnostics</h3><p>Windows development computer → Umbrel computer</p></div><button onClick={refresh}>Run checks</button></div><dl><div><dt>Development profile</dt><dd>{manager?.profile??"Manager unavailable"}</dd></div><div><dt>Rusty Kaspad RPC</dt><dd>{manager?.node.endpoint??"Not checked"} — {manager?.node.reachable?`reachable in ${manager.node.latency_ms} ms`:manager?.node.error??"unavailable"}</dd></div><div><dt>Rusty bridge API</dt><dd>{manager?.bridge.api_url??"Not checked"} — {manager?.bridge.api.reachable?"reachable":manager?.bridge.api.error??"unavailable"}</dd></div><div><dt>Process controls</dt><dd>{manager?.bridge.managed?"Enabled":"Disabled in Windows development profile"}</dd></div></dl></section>:section==="Settings"?<section className="settings-page">
   <div className="settings-intro"><div><h2>Bridge settings</h2><p>Automatic is recommended for most miners. Wallets, passwords, and the Umbrel node connection are never stored here.</p></div><span>Protected local configuration</span></div>
   {settingsNotice&&<div className={`settings-notice ${settingsNotice.kind}`} role="status">{settingsNotice.text}</div>}
   {settingsLoading&&!settings?<section className="panel settings-loading">Loading safe bridge settings…</section>:settings&&settingsModel?<>
    <section className="panel preset-panel"><div className="settings-heading"><div><h3>Choose a setup</h3><p>You can return to a recommended setup at any time.</p></div></div><div className="preset-grid">
     <button className={settings.preset==="automatic"?"selected":""} onClick={()=>choosePreset("automatic")}><strong>Automatic</strong><small>Recommended</small><span>Safe adaptive difficulty for modern Kaspa ASIC miners.</span></button>
     <button className={settings.preset==="iceriver"?"selected":""} onClick={()=>choosePreset("iceriver")}><strong>IceRiver</strong><small>Curated ASIC preset</small><span>Proven defaults for the KS7 Lite and compatible IceRiver miners.</span></button>
     <button className={settings.preset==="custom"?"selected":""} onClick={()=>choosePreset("custom")}><strong>Custom</strong><small>Advanced</small><span>Adjust only the approved bridge tuning below.</span></button>
    </div></section>
    <section className="settings-columns"><section className="panel settings-form"><div className="settings-heading"><div><h3>Miner connection</h3><p>Use these values when connecting miners on your local network.</p></div></div>
     <label><span>Stratum port<small>Protected to match Umbrel’s LAN service.</small></span><input aria-label="Stratum port" type="number" value={settings.stratumPort} disabled readOnly/></label>
     <label><span>Minimum share difficulty<small>Must be a power of two. 2048 is recommended.</small></span><input aria-label="Minimum share difficulty" type="number" min="1" step="1" value={settings.minimumShareDifficulty} onChange={event=>changeSetting("minimumShareDifficulty",Number(event.target.value))}/></label>
     <label><span>Extra nonce size<small>Keep 2 for IceRiver compatibility.</small></span><input aria-label="Extra nonce size" type="number" min="1" max="4" value={settings.extranonceSize} onChange={event=>changeSetting("extranonceSize",Number(event.target.value))}/></label>
    </section><section className="panel settings-form"><div className="settings-heading"><div><h3>Automatic difficulty</h3><p>Keeps share submissions steady as miner speed changes.</p></div></div>
     <label className="toggle-row"><span>Variable difficulty<small>Recommended for stable ASIC mining.</small></span><input aria-label="Variable difficulty" type="checkbox" checked={settings.variableDifficulty} onChange={event=>changeSetting("variableDifficulty",event.target.checked)}/></label>
     <label><span>Target shares per minute<small>30 is the tested default.</small></span><input aria-label="Target shares per minute" type="number" min="1" max="120" value={settings.sharesPerMinute} onChange={event=>changeSetting("sharesPerMinute",Number(event.target.value))}/></label>
     <label className="toggle-row"><span>Power-of-two clamping<small>Required with variable difficulty for ASIC compatibility.</small></span><input aria-label="Power-of-two clamping" type="checkbox" checked={settings.powerOfTwoClamp} onChange={event=>changeSetting("powerOfTwoClamp",event.target.checked)}/></label>
    </section></section>
    <section className="panel protected-settings"><div><i>✓</i><span><strong>Umbrel node connection is protected</strong><small>{settingsModel.protected.nodeConnection}. It cannot be changed from this page.</small></span></div><div><i>✓</i><span><strong>No wallet or credentials</strong><small>This settings model does not read, accept, or store wallet information, miner passwords, or credentials.</small></span></div></section>
    {settingsIssues.length>0&&<section className="settings-errors" role="alert"><strong>Please check these settings:</strong><ul>{settingsIssues.map((item,index)=><li key={`${item.field}-${index}`}>{item.message}</li>)}</ul></section>}
    <section className="save-bar"><div><strong>Saving briefly interrupts miners</strong><span>The bridge restarts and checks itself. If it cannot start safely, the previous working settings are restored automatically.</span></div><button className="restart" disabled={settingsSaving||!manager?.bridge.managed} onClick={saveSettings}>{settingsSaving?"Saving and checking…":"Save and restart bridge"}</button></section>
   </>:<section className="panel settings-loading"><p>Settings are unavailable.</p><button onClick={loadSettings}>Try again</button></section>}
  </section>:<section className="panel empty"><b>≡</b><h2>{section}</h2><p>This module is scheduled for the next implementation milestone. The responsive application shell is ready.</p><button className="restart" onClick={()=>setSection("Overview")}>Return to overview</button></section>}
   <footer className="workspace-footer"><span>Developed by</span><a href="https://github.com/NoillioN-Labs" target="_blank" rel="noreferrer">NoillioN-Labs</a></footer>
  </section>
 </main>
}

