"use client";
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";

const nav = ["Overview","Miners","Logs","Diagnostics","Settings"];
type ManagerStatus={appVersion:string;bridgeVersion:string;profile:string;node:{endpoint:string;reachable:boolean;latency_ms:number;error:string|null};stratum?:{port:number;reachable:boolean;latency_ms:number;error:string|null};bridge:{managed:boolean;state:string;uptime_seconds:number;api_url:string;api:{reachable:boolean;error:string|null;status?:{kaspad_version?:string}}};checked_at:string};
type BridgeWorker={instance?:string;worker?:string;workerName?:string;name?:string;hashrate?:number;hashrateGhs?:number;shares?:number;acceptedShares?:number;blocks?:number;status?:string};
type BridgeBlock={instance?:string;worker?:string;timestamp?:string};
type BridgeStats={activeWorkers?:number;totalBlocks?:number;totalShares?:number;networkHashrate?:number;bridgeUptime?:number;blocks?:BridgeBlock[];workers?:BridgeWorker[]};
type BridgeSettings={preset:"automatic"|"iceriver"|"custom";stratumPort:number;variableDifficulty:boolean;sharesPerMinute:number;powerOfTwoClamp:boolean;extranonceSize:number;minimumShareDifficulty:number};
type SettingsModel={settings:BridgeSettings;presets:{automatic:BridgeSettings&{label:string};iceriver:BridgeSettings&{label:string}};protected:{nodeConnection:string;credentialsStored:boolean}};
type SettingsIssue={field:string;message:string};
type LogEntry={timestamp:string;source:string;line:string};
type PeriodMetric={windowSeconds:number;sampleCount:number;coverageSeconds:number;averageHashrateHs:number;availabilityRatio:number|null;expectedBlocksObserved:number;actualBlocksObserved:number;luckRatio:number|null;averageNetworkHashrateHs:number;averageNetworkDifficulty:number;networkBlocksObserved:number;acceptedShares:number;staleShares:number|null;invalidShares:number|null;rejectionRate:number|null;sharesPerMinute:number|null;lastSeenAt?:string|null;lastAcceptedShareAt?:string|null};
type MiningOutlookWorker={instance:string;worker:string;averageHashrateHs:number;blocksFound:number;lastBlockAt:string|null;expectedBlocksObserved:number;expectedBlocksNextWindow:number|null;probabilityNextWindow:number|null;probabilityNoBlockNextWindow:number|null;estimatedTimeToBlockSeconds:number|null;periods:Record<HistoryRange,PeriodMetric|null>};
type HistoryPoint={timestamp:number;hashrateHs:number};
type RecentBlock={instance:string;worker:string;timestamp:string|null;networkDifficulty:number;networkBlockCount:number;effortPercent:number|null;completeRound:boolean};
type MiningOutlook={windowDays:number;sampleCount:number;coverageSeconds:number;startedAt:string|null;lastSampleAt:string|null;averageHashrateHs:number;averageNetworkHashrateHs:number;averageNetworkDifficulty:number;networkBlocksObserved:number;blocksFound:number;lastBlockAt:string|null;expectedBlocksObserved:number;luckRatio:number|null;currentRoundEffortPercent:number|null;currentRoundStartedAt:string|null;currentRoundComplete:boolean;blockHistoryDays:number;expectedBlocksNextWindow:number|null;probabilityNextWindow:number|null;probabilityNoBlockNextWindow:number|null;estimatedTimeToBlockSeconds:number|null;periods:Record<HistoryRange,PeriodMetric>;charts:Record<HistoryRange,HistoryPoint[]>;recentBlocks:RecentBlock[];workers:MiningOutlookWorker[]};
type HistoryRange="oneHour"|"sixHours"|"twentyFourHours"|"sevenDays";
type ChartRange="tenMinutes"|HistoryRange;
type DashboardMetricSample={timestamp:number;hashrateHs:number;connectedMiners:number;acceptedSharesTotal:number};
type DashboardMetrics={retentionMinutes:number;sampleIntervalSeconds:number;acceptedSharesTotal:number;startedAt:string|null;lastSampleAt:string|null;samples:DashboardMetricSample[]};
type DonationCurrency={id:"kaspa"|"bitcoin";label:string;address:string};
type DonationSupport={enabled:boolean;currencies:DonationCurrency[]};
const formatHashrate=(value?:number)=>value?value>=1e18?`${(value/1e18).toFixed(2)} EH/s`:value>=1e12?`${(value/1e12).toFixed(2)} TH/s`:`${(value/1e9).toFixed(2)} GH/s`:"—";
const workerHashrateGhs=(worker:BridgeWorker)=>worker.hashrateGhs??worker.hashrate??0;
const formatWorkerHashrate=(worker:BridgeWorker)=>formatHashrate(workerHashrateGhs(worker)*1e9);
const blockTime=(value?:string)=>{if(!value)return 0;const numeric=Number(value);const date=new Date(Number.isFinite(numeric)?numeric*1000:value);return date.getTime()};
const formatBlockTime=(value?:string)=>{const time=blockTime(value);return time?new Date(time).toLocaleString([],{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Never"};
const formatProbability=(value:number|null)=>value===null?"Collecting…":value<0.001?"<0.1%":`${(value*100).toFixed(value<0.1?1:0)}%`;
const formatExpectedBlocks=(value:number|null)=>value===null?"—":value<0.01?"<0.01":value<10?value.toFixed(2):value.toFixed(1);
const formatEstimatedTime=(seconds:number|null)=>{if(seconds===null)return "Collecting…";const days=seconds/86400;if(days>=730)return `${(days/365).toFixed(1)} years`;if(days>=1)return `${days.toFixed(days<10?1:0)} days`;const hours=seconds/3600;return hours>=1?`${hours.toFixed(hours<10?1:0)} hours`:`${Math.max(1,Math.round(seconds/60))} min`};
const formatCoverage=(seconds:number)=>seconds>=86400?`${(seconds/86400).toFixed(1)} days`:seconds>=3600?`${(seconds/3600).toFixed(1)} hours`:`${Math.round(seconds/60)} min`;
const formatPercent=(value:number|null,digits=1)=>value===null?"Not reported":`${(value*100).toFixed(digits)}%`;
const formatEffort=(value:number|null,complete=true)=>value===null?"Collecting…":`${complete?"":"≥ "}${value.toFixed(0)}%`;
const formatLuck=(value:number|null)=>value===null?"Collecting…":`${(value*100).toFixed(0)}%`;
const formatRelativeTime=(value?:string|null)=>{if(!value)return "Not observed";const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`};
const formatShareHealth=(period?:PeriodMetric|null)=>period?.rejectionRate===null||period?.rejectionRate===undefined?"Not reported":`${((1-period.rejectionRate)*100).toFixed(1)}% accepted`;
const rangeLabels:Record<ChartRange,string>={tenMinutes:"10m",oneHour:"1h",sixHours:"6h",twentyFourHours:"24h",sevenDays:"7d"};

export default function Home(){
 const [section,setSection]=useState("Overview"); const [manager,setManager]=useState<ManagerStatus|null>(null); const [stats,setStats]=useState<BridgeStats|null>(null); const [dashboardMetrics,setDashboardMetrics]=useState<DashboardMetrics|null>(null); const [error,setError]=useState("");
 const [settingsModel,setSettingsModel]=useState<SettingsModel|null>(null); const [settings,setSettings]=useState<BridgeSettings|null>(null); const [settingsLoading,setSettingsLoading]=useState(false); const [settingsSaving,setSettingsSaving]=useState(false); const [settingsNotice,setSettingsNotice]=useState<{kind:"success"|"error"|"rollback";text:string}|null>(null); const [settingsIssues,setSettingsIssues]=useState<SettingsIssue[]>([]);
 const [logs,setLogs]=useState<LogEntry[]>([]); const [logsLoading,setLogsLoading]=useState(false); const [logsError,setLogsError]=useState(""); const [logSource,setLogSource]=useState("all"); const [logQuery,setLogQuery]=useState("");
 const [miningOutlook,setMiningOutlook]=useState<MiningOutlook|null>(null); const [chartRange,setChartRange]=useState<ChartRange>("tenMinutes");
 const [donationSupport,setDonationSupport]=useState<DonationSupport|null>(null); const [donationsOpen,setDonationsOpen]=useState(false); const [mobileMenuOpen,setMobileMenuOpen]=useState(false);
 const [diagnosticsRunning,setDiagnosticsRunning]=useState(false);
 const managerBase=process.env.NEXT_PUBLIC_MANAGER_URL??"";
 const refresh=useCallback(async()=>{try{const statusResponse=await fetch(`${managerBase}/api/manager/status`,{cache:"no-store"});if(!statusResponse.ok)throw new Error(`Manager returned ${statusResponse.status}`);const status=await statusResponse.json();setManager(status);setError("");if(status.bridge.api.reachable){const statsResponse=await fetch(`${managerBase}/api/manager/stats`,{cache:"no-store"});if(statsResponse.ok)setStats(await statsResponse.json());else setStats(null)}else setStats(null)}catch(reason){setStats(null);setError(reason instanceof Error?reason.message:"Manager unavailable")}},[managerBase]);
 useEffect(()=>{const initial=window.setTimeout(refresh,0);const timer=window.setInterval(refresh,5000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh]);
 const loadSettings=useCallback(async()=>{setSettingsLoading(true);try{const response=await fetch(`${managerBase}/api/manager/settings`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Settings are unavailable");setSettingsModel(body);setSettings(body.settings);setSettingsIssues([]);setSettingsNotice(null)}catch(reason){setSettingsNotice({kind:"error",text:reason instanceof Error?reason.message:"Settings are unavailable"})}finally{setSettingsLoading(false)}},[managerBase]);
 const loadLogs=useCallback(async()=>{setLogsLoading(true);try{const response=await fetch(`${managerBase}/api/manager/logs?limit=200`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Logs are unavailable");setLogs(Array.isArray(body.lines)?body.lines:[]);setLogsError("")}catch(reason){setLogsError(reason instanceof Error?reason.message:"Logs are unavailable")}finally{setLogsLoading(false)}},[managerBase]);
 const loadMiningOutlook=useCallback(async()=>{try{const response=await fetch(`${managerBase}/api/manager/history`,{cache:"no-store"});if(response.ok)setMiningOutlook(await response.json())}catch{}},[managerBase]);
 const loadDashboardMetrics=useCallback(async()=>{try{const response=await fetch(`${managerBase}/api/manager/metrics`,{cache:"no-store"});if(response.ok)setDashboardMetrics(await response.json())}catch{}},[managerBase]);
 const loadDonationSupport=useCallback(async()=>{try{const response=await fetch(`${managerBase}/api/manager/support`,{cache:"no-store"});if(response.ok)setDonationSupport(await response.json())}catch{}},[managerBase]);
 useEffect(()=>{const initial=window.setTimeout(loadMiningOutlook,0);const timer=window.setInterval(loadMiningOutlook,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[loadMiningOutlook]);
 useEffect(()=>{const initial=window.setTimeout(loadDashboardMetrics,0);const timer=window.setInterval(loadDashboardMetrics,5_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[loadDashboardMetrics]);
 useEffect(()=>{const initial=window.setTimeout(loadDonationSupport,0);return()=>window.clearTimeout(initial)},[loadDonationSupport]);
 useEffect(()=>{if(section!=="Logs")return;const initial=window.setTimeout(loadLogs,0);const timer=window.setInterval(loadLogs,5000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[section,loadLogs]);
 const choosePreset=(preset:"automatic"|"iceriver"|"custom")=>{if(!settingsModel||!settings)return;if(preset==="custom")setSettings({...settings,preset});else{const selected=settingsModel.presets[preset];setSettings({preset,stratumPort:selected.stratumPort,variableDifficulty:selected.variableDifficulty,sharesPerMinute:selected.sharesPerMinute,powerOfTwoClamp:selected.powerOfTwoClamp,extranonceSize:selected.extranonceSize,minimumShareDifficulty:selected.minimumShareDifficulty})}setSettingsIssues([]);setSettingsNotice(null)};
 const changeSetting=<K extends keyof BridgeSettings>(key:K,value:BridgeSettings[K])=>setSettings(current=>current?{...current,[key]:value,...(key==="preset"?{}:{preset:"custom" as const})}:current);
 const saveSettings=async()=>{if(!settings)return;setSettingsSaving(true);setSettingsIssues([]);setSettingsNotice(null);try{const response=await fetch(`${managerBase}/api/manager/settings`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const body=await response.json();if(!response.ok){if(Array.isArray(body.issues))setSettingsIssues(body.issues);if(body.result==="rolled_back")setSettingsNotice({kind:"rollback",text:body.rollback?.healthy?"Those settings did not start safely. The previous working settings were restored and the bridge is healthy again.":"The previous settings were restored, but the bridge still needs attention."});else setSettingsNotice({kind:"error",text:body.error||"Settings could not be saved."});return}setSettings(body.settings);setSettingsNotice({kind:"success",text:"Settings saved. The bridge restarted and passed its health check."});await refresh()}catch(reason){setSettingsNotice({kind:"error",text:reason instanceof Error?reason.message:"Settings could not be saved."})}finally{setSettingsSaving(false)}};
 const control=async(action:"start"|"stop"|"restart")=>{try{const response=await fetch(`${managerBase}/api/manager/bridge/${action}`,{method:"POST"});if(!response.ok)throw new Error((await response.json()).error||`Action failed (${response.status})`);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Action failed")}};
 const runDiagnostics=async()=>{setDiagnosticsRunning(true);await refresh();setDiagnosticsRunning(false)};
 const selectSection=(nextSection:string)=>{setSection(nextSection);setMobileMenuOpen(false);if(nextSection==="Settings"&&!settingsModel)void loadSettings()};
 const running=manager?.bridge.state==="running"||manager?.bridge.api.reachable===true;
 const hasLiveStats=manager?.bridge.api.reachable===true&&stats!==null;
 const workers=hasLiveStats&&Array.isArray(stats.workers)?stats.workers:[];
 const visibleWorkers=workers.slice(0,5);
 const combinedMinerHashrate=workers.reduce((total,worker)=>total+workerHashrateGhs(worker),0)*1e9;
 const connectedMinerCount=hasLiveStats?(stats.activeWorkers??workers.length):0;
 const chartPoints:HistoryPoint[]=chartRange==="tenMinutes"?(dashboardMetrics?.samples.map(sample=>({timestamp:sample.timestamp,hashrateHs:sample.hashrateHs}))??[]):(miningOutlook?.charts?.[chartRange]??[]);
 const history=chartPoints.map(sample=>sample.hashrateHs);
 const historyMax=Math.max(1,...history);
 const selectedPeriod=chartRange==="tenMinutes"?null:miningOutlook?.periods?.[chartRange];
 const historyAverage=selectedPeriod?.averageHashrateHs??(history.length?history.reduce((total,value)=>total+value,0)/history.length:0);
 const outlookWorkerFor=(worker:BridgeWorker,name:string)=>miningOutlook?.workers.find(item=>item.worker===name&&(!worker.instance||!item.instance||item.instance===worker.instance));
 const metricSource=hasLiveStats?"Live bridge API":"Waiting for bridge";
 const recordedShares=dashboardMetrics?.acceptedSharesTotal??stats?.totalShares;
 const oneHourPerformance=miningOutlook?.periods?.oneHour;
 const lastAcceptedShareAt=miningOutlook?.periods.sevenDays.lastAcceptedShareAt??null;
 const metrics=[["Connected miners",hasLiveStats?(stats.activeWorkers??workers.length).toString():"—",metricSource],["Miner hashrate",hasLiveStats?formatHashrate(combinedMinerHashrate):"—",metricSource],["Accepted shares",recordedShares?.toLocaleString()??"—",dashboardMetrics?"Recorded by manager":metricSource],["Node latency",manager?.node.reachable?`${manager.node.latency_ms} ms`:"—",manager?.node.endpoint??"Not checked"]];
 const normalizedLogQuery=logQuery.trim().toLowerCase();
 const filteredLogs=logs.filter(entry=>(logSource==="all"||entry.source===logSource)&&(!normalizedLogQuery||entry.line.toLowerCase().includes(normalizedLogQuery))).slice().reverse();
 const bridgeLogCount=logs.filter(entry=>entry.source==="bridge").length;
 const managerLogCount=logs.filter(entry=>entry.source==="manager").length;
 const diagnosticsHealthy=Boolean(manager?.node.reachable&&manager?.bridge.api.reachable&&manager?.stratum?.reachable);
 const supervisorHealthy=Boolean(manager&&(manager.bridge.managed?running:true));
 const healthSummary=manager?.node.reachable?(manager.bridge.api.reachable?"Healthy":"Ready for bridge"):"Attention";
 const stratumHost=useSyncExternalStore(()=>()=>{},()=>window.location.hostname,()=>"your-umbrel-host");
 return <main className="shell">
  <aside><div className="mobile-nav-bar"><div className="brand">
   {/* SVG stays crisp at every Umbrel display density. */}
   {/* eslint-disable-next-line @next/next/no-img-element */}
   <img src="/kaspa-logo.svg" alt="Kaspa"/><small>Stratum Bridge Manager</small></div>
   <button className="mobile-nav-toggle" type="button" aria-label={mobileMenuOpen?"Close navigation menu":"Open navigation menu"} aria-expanded={mobileMenuOpen} aria-controls="primary-navigation" onClick={()=>setMobileMenuOpen(value=>!value)}><span/><span/><span/></button></div>
   <nav id="primary-navigation" className={mobileMenuOpen?"mobile-open":""} aria-label="Main navigation">{nav.map(x=><button key={x} className={x===section?"active":""} onClick={()=>selectSection(x)}>{x}</button>)}</nav>
   <div className="aside-status"><div className="aside-connection"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Rusty Kaspad connected":"Rusty Kaspad unavailable"}</div><dl><div><dt>Node version</dt><dd>{manager?.bridge.api.status?.kaspad_version??"Checking…"}</dd></div><div><dt>Bridge version</dt><dd>{manager?.bridgeVersion??"Checking…"}</dd></div><div><dt>App version</dt><dd>{manager?.appVersion??"Checking…"}</dd></div></dl></div>
  </aside>
  <section className="workspace"><header><div><p>LOCAL MINING CONTROL</p><h1>{section}</h1></div><span className="node"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Node reachable":"Checking node"} <b>{manager?.node.latency_ms??"—"} ms</b></span></header>
  {error&&<div className="alert"><strong>Development connection:</strong> {error}. Start the manager on this computer to connect the dashboard.</div>}
  {section==="Overview"?<>
   <section className="hero"><div className="hero-copy"><span className={running?"running":"stopped"}>{running?"● Bridge running":"○ Bridge stopped"}</span><h2>{running?"Mining gateway is online":"Mining gateway is offline"}</h2><p>{running?"Your miners can connect to your own Kaspa node.":"Start the bridge before connecting miners."} <small>{manager?.profile==="umbrel"?"Running locally inside Umbrel.":"Windows development profile connected across your LAN."}</small></p><div className="endpoint"><small>Miner connection address</small><code>{`stratum+tcp://${stratumHost}:5555`}</code></div></div><div className="control"><div className="ring"><b>{running?new Date((manager?.bridge.uptime_seconds??stats?.bridgeUptime??0)*1000).toISOString().slice(11,19):"—"}</b><small>UPTIME</small></div><div className="control-actions"><button disabled={!manager?.bridge.managed||!running} onClick={()=>control("stop")}>Stop</button><button disabled={!manager?.bridge.managed} className="restart" onClick={()=>control(running?"restart":"start")}>{running?"Restart":"Start"}</button></div></div></section>
   <section className="metrics">{metrics.map((m,i)=><article key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={i===0||i===2?"good":""}>{m[2]}</small></article>)}</section>
   <section className="grid"><article className="panel hashrate-panel"><div className="panel-head"><div><h3>Miner hashrate</h3><p>Collected continuously by the manager</p></div><div className="chart-average"><span>{rangeLabels[chartRange]} average</span><strong>{history.length?formatHashrate(historyAverage):"—"}</strong><small>{history.length?`${history.length} readings · ${chartRange==="tenMinutes"?"5-second":"time-bucketed"} history`:"Waiting for readings"}</small></div></div><div className="chart-range" aria-label="Hashrate history range">{(Object.keys(rangeLabels) as ChartRange[]).map(range=><button key={range} className={chartRange===range?"active":""} onClick={()=>setChartRange(range)}>{rangeLabels[range]}</button>)}</div>{history.length>1?<div className="chart live-chart" aria-label={`${rangeLabels[chartRange]} persistent miner hashrate history`}><div className="history-points">{history.map((value,index)=><i key={chartPoints[index]?.timestamp??index} style={{height:`${Math.max(4,value/historyMax*100)}%`}} title={`${new Date(chartPoints[index]?.timestamp??0).toLocaleString()} · ${formatHashrate(value)}`}/>)}</div></div>:<div className="chart-empty"><b>Collecting background readings</b><span>The manager keeps collecting while this page is closed.</span></div>}</article>
   <article className="panel system-health"><div className="panel-head"><div><h3>System health</h3><p>Live management checks</p></div><em>{healthSummary}</em></div>{[["Rusty Kaspad RPC",manager?.node.endpoint??"Checking",manager?.node.reachable?"Active":"Unavailable",manager?.node.reachable],["Bridge API",manager?.bridge.api_url??"Checking",manager?.bridge.api.reachable?"Active":"Stopped",manager?.bridge.api.reachable],["Bridge supervisor",manager?.bridge.managed?"Managed":"Disabled in Windows profile",manager?.bridge.managed?"Active":"Expected",Boolean(manager)],["Runtime profile",manager?.profile??"Checking",manager?"Active":"Unavailable",Boolean(manager)]].map(x=><div className="health" key={String(x[0])}><i className={x[3]?"":"bad"}/><strong>{x[0]}<small>{x[1]}</small></strong><span className={x[2]==="Expected"?"safe":""}>{x[2]}</span></div>)}</article></section>
   <section className="panel miners"><div className="panel-head"><div><h3>Active miners</h3><p>Workers currently connected through the Stratum bridge</p></div><button onClick={()=>selectSection("Miners")}>View all →</button></div>{visibleWorkers.length?<div className="table"><table><thead><tr><th>Worker</th><th>Hashrate</th><th>Last accepted share</th><th>Accepted shares</th><th>Blocks found</th><th>Status</th></tr></thead><tbody>{visibleWorkers.map((worker,index)=>{const name=worker.worker??worker.workerName??worker.name??`Worker ${index+1}`;const status=worker.status??"Unknown";const recorded=outlookWorkerFor(worker,name);return <tr key={`${name}-${index}`}><td data-label="Worker">{name}</td><td data-label="Hashrate">{formatWorkerHashrate(worker)}</td><td data-label="Last accepted share">{formatRelativeTime(recorded?.periods.sevenDays?.lastAcceptedShareAt)}</td><td data-label="Accepted shares">{(worker.acceptedShares??worker.shares??0).toLocaleString()}</td><td data-label="Blocks found">{(worker.blocks??0).toLocaleString()}</td><td data-label="Status" className={status.toLowerCase()}>{status}</td></tr>})}</tbody></table></div>:<div className="miners-empty"><b>No live miner data</b><span>{running?"Miner details will appear when a worker connects.":"Start the bridge to begin monitoring workers."}</span></div>}<div className="miners-foot"><span>Showing up to 5 miners · share freshness is observed locally · blocks are confirmed by your node</span>{workers.length>5&&<button onClick={()=>selectSection("Miners")}>{workers.length-5} more miner{workers.length-5===1?"":"s"} →</button>}</div></section>
  </>:section==="Miners"?<section className="miners-page">
   <section className={`miners-live-strip ${hasLiveStats?"live":"waiting"}`}><div><i/><span><strong>{hasLiveStats?`${connectedMinerCount} miner${connectedMinerCount===1?"":"s"} connected`:running?"Waiting for miners":"Mining bridge is stopped"}</strong><small>{hasLiveStats?"Live data refreshes every 5 seconds.":running?"Connected workers will appear here automatically.":"Start the bridge from Overview before connecting a miner."}</small></span></div><button onClick={refresh}>Refresh now</button></section>
   <section className="miners-summary"><article><span>Connected miners</span><strong>{hasLiveStats?connectedMinerCount:"—"}</strong><small>{hasLiveStats?"Reporting to the bridge":"Waiting for bridge"}</small></article><article><span>Combined hashrate</span><strong>{hasLiveStats?formatHashrate(combinedMinerHashrate):"—"}</strong><small>Current live performance</small></article><article><span>Accepted shares</span><strong>{recordedShares?.toLocaleString()??"—"}</strong><small>{dashboardMetrics?"Since manager records began":"Waiting for manager"}</small></article><article><span>Last accepted share</span><strong className="summary-time">{formatRelativeTime(lastAcceptedShareAt)}</strong><small>{formatShareHealth(oneHourPerformance)} over the last hour</small></article></section>
   <section className="panel performance-windows"><div className="panel-head"><div><h3>Hashrate performance</h3><p>Time-weighted averages retained locally while the dashboard is closed</p></div><span className="outlook-coverage">{miningOutlook?.coverageSeconds?`${formatCoverage(miningOutlook.coverageSeconds)} recorded`:"Collecting history"}</span></div><div className="performance-window-grid">{([['oneHour','1 hour'],['sixHours','6 hours'],['twentyFourHours','24 hours'],['sevenDays','7 days']] as [HistoryRange,string][]).map(([range,label])=>{const period=miningOutlook?.periods?.[range];return <article key={range}><span>{label} average</span><strong>{period?formatHashrate(period.averageHashrateHs):"—"}</strong><small>{period?.coverageSeconds?`${formatCoverage(period.coverageSeconds)} coverage · ${formatPercent(period.availabilityRatio) } online`:"Collecting samples"}</small></article>})}</div><div className="share-activity"><span><b>Accepted in last hour</b>{oneHourPerformance?.acceptedShares?.toLocaleString()??"—"}</span><span><b>Accepted share rate</b>{oneHourPerformance?.sharesPerMinute===null||oneHourPerformance?.sharesPerMinute===undefined?"Collecting…":`${oneHourPerformance.sharesPerMinute.toFixed(1)}/min`}</span><span><b>Share quality</b>{formatShareHealth(oneHourPerformance)}</span><span><b>Last accepted</b>{formatRelativeTime(lastAcceptedShareAt)}</span></div></section>
   <section className="panel mining-outlook"><div className="panel-head"><div><h3>7-day solo mining outlook</h3><p>Locally observed performance, block luck, and forward-looking estimates</p></div><span className="outlook-coverage">{miningOutlook?.coverageSeconds?`${formatCoverage(miningOutlook.coverageSeconds)} recorded`:"Collecting history"}</span></div><div className="outlook-cards expanded"><article><span>7-day average hashrate</span><strong>{miningOutlook?formatHashrate(miningOutlook.averageHashrateHs):"—"}</strong><small>Includes observed online and offline periods</small></article><article><span>Actual versus expected</span><strong>{miningOutlook?.blocksFound??0} / {formatExpectedBlocks(miningOutlook?.expectedBlocksObserved??null)}</strong><small>Confirmed blocks during recorded coverage</small></article><article><span>Observed block luck</span><strong>{formatLuck(miningOutlook?.luckRatio??null)}</strong><small>100% means actual blocks matched the statistical expectation</small></article><article><span>Current round effort</span><strong>{formatEffort(miningOutlook?.currentRoundEffortPercent??null,miningOutlook?.currentRoundComplete??false)}</strong><small>Statistical work since the last confirmed block—not progress</small></article><article><span>Expected next 7 days</span><strong>{formatExpectedBlocks(miningOutlook?.expectedBlocksNextWindow??null)}</strong><small>{formatProbability(miningOutlook?.probabilityNextWindow??null)} chance of at least one block</small></article><article><span>Estimated average wait</span><strong>{formatEstimatedTime(miningOutlook?.estimatedTimeToBlockSeconds??null)}</strong><small>{formatProbability(miningOutlook?.probabilityNoBlockNextWindow??null)} chance of zero blocks in the next 7 days</small></article></div><div className="outlook-inputs"><span><b>Average network hashrate</b>{miningOutlook?formatHashrate(miningOutlook.averageNetworkHashrateHs):"—"}</span><span><b>Average network difficulty</b>{miningOutlook?.averageNetworkDifficulty?miningOutlook.averageNetworkDifficulty.toLocaleString(undefined,{maximumFractionDigits:0}):"—"}</span><span><b>Network blocks observed</b>{miningOutlook?.networkBlocksObserved?.toLocaleString()??"—"}</span><span><b>History samples</b>{miningOutlook?.sampleCount?.toLocaleString()??"0"}</span></div><p className="outlook-note">Effort and luck describe past statistical outcomes. Forecasts use changing network conditions and are estimates—not promises that a block will be found.</p></section>
   <section className="miners-connection"><div><span>MINER CONNECTION ADDRESS</span><h2>Connect miners to your Umbrel</h2><p>Enter this address as the pool URL in each miner. Give every miner a unique worker name so it is easy to identify below.</p></div><code>{`stratum+tcp://${stratumHost}:5555`}</code></section>
   <section className="panel miners-directory"><div className="panel-head"><div><h3>Miner directory</h3><p>Live status with locally retained performance windows</p></div><span className="directory-count">{hasLiveStats?`${workers.length} shown`:"Not connected"}</span></div>{workers.length?<div className="table"><table><thead><tr><th>Worker</th><th>Current</th><th>1 hour</th><th>6 hours</th><th>24 hours</th><th>Last accepted</th><th>Share health</th><th>Blocks</th><th>Status</th></tr></thead><tbody>{workers.map((worker,index)=>{const name=worker.worker??worker.workerName??worker.name??`Worker ${index+1}`;const status=worker.status??"Unknown";const statusClass=status.toLowerCase()==="online"?"online":status.toLowerCase()==="idle"?"idle":"";const recorded=outlookWorkerFor(worker,name);return <tr key={`${name}-${index}`}><td data-label="Worker"><strong>{name}</strong><small>{worker.instance??"Default instance"}</small></td><td data-label="Current hashrate">{formatWorkerHashrate(worker)}</td><td data-label="1-hour average">{formatHashrate(recorded?.periods.oneHour?.averageHashrateHs)}</td><td data-label="6-hour average">{formatHashrate(recorded?.periods.sixHours?.averageHashrateHs)}</td><td data-label="24-hour average">{formatHashrate(recorded?.periods.twentyFourHours?.averageHashrateHs)}</td><td data-label="Last accepted share">{formatRelativeTime(recorded?.periods.sevenDays?.lastAcceptedShareAt)}</td><td data-label="Share health">{formatShareHealth(recorded?.periods.oneHour)}</td><td data-label="Blocks found">{(worker.blocks??0).toLocaleString()}</td><td data-label="Status"><span className={`miner-status ${statusClass}`}><i/>{status}</span></td></tr>})}</tbody></table></div>:<div className="miners-directory-empty"><b>{running?"No miners connected yet":"Bridge is offline"}</b><span>{running?"Check the connection address in your miner, then allow up to a minute for its first reading.":"Return to Overview and start the mining bridge."}</span>{!running&&<button className="restart" onClick={()=>setSection("Overview")}>Go to Overview</button>}</div>}<div className="miners-directory-foot"><span>Live block and share totals come from the current bridge session. Performance windows remain available after restarts.</span><span>{manager?.checked_at?`Last checked ${new Date(manager.checked_at).toLocaleTimeString()}`:"Waiting for first check"}</span></div></section>
   <section className="panel recent-blocks"><div className="panel-head"><div><h3>Recent confirmed blocks</h3><p>Solo-mined blocks observed locally and retained for up to {miningOutlook?.blockHistoryDays??90} days</p></div><span className="directory-count">{miningOutlook?.recentBlocks.length??0} shown</span></div>{miningOutlook?.recentBlocks.length?<div className="table"><table><thead><tr><th>Time found</th><th>Worker</th><th>Network block count</th><th>Difficulty</th><th>Round effort</th><th>Status</th></tr></thead><tbody>{miningOutlook.recentBlocks.map((block,index)=><tr key={`${block.timestamp}-${block.worker}-${index}`}><td data-label="Time found">{formatBlockTime(block.timestamp??undefined)}</td><td data-label="Worker"><strong>{block.worker}</strong><small>{block.instance||"Default instance"}</small></td><td data-label="Network block count">{block.networkBlockCount?block.networkBlockCount.toLocaleString():"Not recorded"}</td><td data-label="Difficulty">{block.networkDifficulty?block.networkDifficulty.toLocaleString(undefined,{maximumFractionDigits:0}):"Not recorded"}</td><td data-label="Round effort"><strong>{formatEffort(block.effortPercent,block.completeRound)}</strong></td><td data-label="Status"><span className="block-confirmed"><i/>Confirmed blue</span></td></tr>)}</tbody></table></div>:<div className="outlook-empty"><b>No confirmed blocks recorded yet</b><span>New blocks will appear after the bridge reports them and your node confirms them blue.</span></div>}<p className="outlook-note">Round effort is statistical work between confirmed blocks. More than 100% is normal and does not mean a block is overdue.</p></section>
   <section className="panel miner-outlook-table"><div className="panel-head"><div><h3>Per-miner 7-day outlook</h3><p>Durable local history remains available after the bridge or app restarts</p></div></div>{miningOutlook?.workers.length?<div className="table"><table><thead><tr><th>Worker</th><th>7-day average</th><th>Actual / expected</th><th>Last block</th><th>Expected next 7 days</th><th>7-day chance</th><th>Average wait</th></tr></thead><tbody>{miningOutlook.workers.map(worker=><tr key={`${worker.instance}-${worker.worker}`}><td data-label="Worker"><strong>{worker.worker}</strong><small>{worker.instance||"Default instance"}</small></td><td data-label="7-day average">{formatHashrate(worker.averageHashrateHs)}</td><td data-label="Actual / expected">{worker.blocksFound.toLocaleString()} / {formatExpectedBlocks(worker.expectedBlocksObserved)}</td><td data-label="Last block">{formatBlockTime(worker.lastBlockAt??undefined)}</td><td data-label="Expected next 7 days">{formatExpectedBlocks(worker.expectedBlocksNextWindow)}</td><td data-label="7-day chance"><strong>{formatProbability(worker.probabilityNextWindow)}</strong></td><td data-label="Average wait">{formatEstimatedTime(worker.estimatedTimeToBlockSeconds)}</td></tr>)}</tbody></table></div>:<div className="outlook-empty"><b>Collecting the first history samples</b><span>Leave the app running. Estimates begin automatically after the manager observes changes in the network block count.</span></div>}</section>
  </section>:section==="Logs"?<section className="logs-page">
   <section className="logs-intro"><div><span><i/>LOCAL ACTIVITY</span><h2>Live application logs</h2><p>Recent messages from the Stratum bridge and its manager. Nothing on this page is uploaded or stored outside your Umbrel.</p></div><button onClick={loadLogs} disabled={logsLoading}>{logsLoading?"Refreshing…":"Refresh now"}</button></section>
   <section className="logs-summary"><article><span>Entries loaded</span><strong>{logs.length}</strong><small>Latest 200 maximum</small></article><article><span>Bridge messages</span><strong>{bridgeLogCount}</strong><small>Mining and worker activity</small></article><article><span>Manager messages</span><strong>{managerLogCount}</strong><small>Starts, stops, and settings</small></article></section>
   <section className="panel logs-viewer"><div className="logs-toolbar"><div className="log-source-filter" aria-label="Log source"><button className={logSource==="all"?"active":""} onClick={()=>setLogSource("all")}>All activity</button><button className={logSource==="bridge"?"active":""} onClick={()=>setLogSource("bridge")}>Bridge</button><button className={logSource==="manager"?"active":""} onClick={()=>setLogSource("manager")}>Manager</button></div><label className="log-search"><span>Search logs</span><input aria-label="Search logs" type="search" value={logQuery} placeholder="Type to filter messages" onChange={event=>setLogQuery(event.target.value)}/></label></div>
    {logsError&&<div className="logs-error" role="alert">{logsError}. The page will try again automatically.</div>}
    {filteredLogs.length?<ol className="log-list">{filteredLogs.map((entry,index)=>{const date=new Date(entry.timestamp);const time=Number.isNaN(date.getTime())?"Unknown time":date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});const source=entry.source==="bridge"?"Bridge":entry.source==="manager"?"Manager":entry.source;return <li key={`${entry.timestamp}-${index}`}><time dateTime={entry.timestamp}>{time}</time><span className={`log-source ${entry.source}`}>{source}</span><code>{entry.line}</code></li>})}</ol>:<div className="logs-empty"><b>{logsLoading?"Loading recent activity…":logs.length?"No messages match these filters":"No log messages yet"}</b><span>{logs.length?"Try a different source or search term.":"New bridge and manager activity will appear here automatically."}</span></div>}
    <div className="logs-foot"><span>Newest messages appear first · refreshes every 5 seconds</span><span>Kept in memory only and cleared when the app restarts</span></div>
   </section>
  </section>:section==="Diagnostics"?<section className="diagnostics-page">
   <section className={`diagnostics-banner ${diagnosticsHealthy?"healthy":"attention"}`}><div><i>{diagnosticsHealthy?"✓":"!"}</i><span><small>SYSTEM READINESS</small><strong>{diagnosticsHealthy?"Everything is ready for mining":"One or more checks need attention"}</strong><p>{diagnosticsHealthy?"Your node, bridge, and miner connection port are responding normally.":"Review the checks below for the part that is not responding."}</p></span></div><button onClick={runDiagnostics} disabled={diagnosticsRunning}>{diagnosticsRunning?"Running checks…":"Run checks now"}</button></section>
   <section className="diagnostics-summary"><article><span>Overall status</span><strong>{diagnosticsHealthy?"Ready":"Attention"}</strong><small>Local mining services</small></article><article><span>Node latency</span><strong>{manager?.node.reachable?`${manager.node.latency_ms} ms`:"—"}</strong><small>Rusty Kaspad RPC</small></article><article><span>Bridge uptime</span><strong>{running?new Date((manager?.bridge.uptime_seconds??0)*1000).toISOString().slice(11,19):"—"}</strong><small>Current running session</small></article><article><span>Connected miners</span><strong>{hasLiveStats?connectedMinerCount:"—"}</strong><small>Live bridge workers</small></article></section>
   <section className="diagnostics-grid"><section className="panel diagnostics-checks"><div className="panel-head"><div><h3>Live service checks</h3><p>Read-only checks performed inside this app</p></div><span className="diagnostics-time">{manager?.checked_at?`Checked ${new Date(manager.checked_at).toLocaleTimeString()}`:"Waiting for first check"}</span></div>
    {[["Rusty Kaspad node",manager?.node.reachable,manager?.node.reachable?`Version ${manager.bridge.api.status?.kaspad_version??"unknown"} · ${manager.node.latency_ms} ms`:manager?.node.error??"No response","Provides blocks and network data"],["Stratum Bridge API",manager?.bridge.api.reachable,manager?.bridge.api.reachable?"Statistics API is responding":manager?.bridge.api.error??"No response","Supplies miner and share statistics"],["Stratum listener",manager?.stratum?.reachable,manager?.stratum?.reachable?`TCP port ${manager.stratum.port} is accepting connections`:manager?.stratum?.error??"Port 5555 is not responding","Accepts connections from ASIC miners"],["Bridge supervisor",supervisorHealthy,manager?.bridge.managed?(running?"Managed process is running":"Managed process is stopped"):"Controls are not used in this profile","Starts and restarts the mining bridge"]].map(check=><div className="diagnostic-check" key={String(check[0])}><i className={check[1]?"pass":"fail"}>{check[1]?"✓":"!"}</i><span><strong>{check[0]}</strong><small>{check[3]}</small></span><div><b>{check[1]?"Working":"Needs attention"}</b><small>{check[2]}</small></div></div>)}
   </section><section className="panel diagnostics-details"><div className="panel-head"><div><h3>Runtime details</h3><p>Versions and local connection information</p></div></div><dl><div><dt>Miner address</dt><dd>{`stratum+tcp://${stratumHost}:5555`}</dd></div><div><dt>Node version</dt><dd>{manager?.bridge.api.status?.kaspad_version??"Checking…"}</dd></div><div><dt>Bridge version</dt><dd>{manager?.bridgeVersion??"Checking…"}</dd></div><div><dt>App version</dt><dd>{manager?.appVersion??"Checking…"}</dd></div><div><dt>Runtime profile</dt><dd>{manager?.profile??"Checking…"}</dd></div></dl></section></section>
   <section className="panel diagnostics-help"><div className="panel-head"><div><h3>If something is not working</h3><p>Start with the check that shows “Needs attention”</p></div></div><div className="diagnostics-help-grid"><article><b>1</b><span><strong>Node unavailable</strong><small>Confirm the Rusty Kaspad app is installed, running, and fully started.</small></span></article><article><b>2</b><span><strong>Bridge stopped</strong><small>Return to Overview and select Start or Restart.</small></span></article><article><b>3</b><span><strong>Miner not connecting</strong><small>Check the miner’s pool address, local network, and TCP port 5555.</small></span></article></div></section>
  </section>:section==="Settings"?<section className="settings-page">
   <div className="settings-intro"><div><h2>Bridge settings</h2><p>Automatic is recommended for most miners. Wallets, passwords, and the Umbrel node connection are never stored here.</p></div><span>Protected local configuration</span></div>
   {settingsNotice&&<div className={`settings-notice ${settingsNotice.kind}`} role="status">{settingsNotice.text}</div>}
   {settingsLoading&&!settings?<section className="panel settings-loading">Loading safe bridge settings…</section>:settings&&settingsModel?<>
    <section className="panel preset-panel"><div className="settings-heading"><div><h3>Choose a setup</h3><p>You can return to a recommended setup at any time.</p></div></div><div className="preset-grid">
     <button className={settings.preset==="automatic"?"selected":""} onClick={()=>choosePreset("automatic")}><strong>Automatic</strong><small>Recommended</small><span>Safe adaptive difficulty for modern Kaspa ASIC miners.</span></button>
     <button className={settings.preset==="iceriver"?"selected":""} onClick={()=>choosePreset("iceriver")}><strong>IceRiver</strong><small>Curated ASIC preset</small><span>Proven defaults for the KS7 Lite and compatible IceRiver miners.</span></button>
     <button className={settings.preset==="custom"?"selected":""} onClick={()=>choosePreset("custom")}><strong>Custom</strong><small>Advanced</small><span>Adjust only the approved bridge tuning below.</span></button>
    </div></section>
    <section className="settings-columns"><section className="panel settings-form"><div className="settings-heading"><div><h3>Miner connection</h3><p>Use these values when connecting miners on your local network.</p></div></div>
     <label><span>Stratum port<small>Protected to match Umbrel’s LAN service.</small></span><input aria-label="Stratum port" type="number" value={settings.stratumPort} disabled readOnly/></label>
     <label><span>Minimum share difficulty<small>Must be a power of two. 2048 is recommended.</small></span><input aria-label="Minimum share difficulty" type="number" min="1" step="1" value={settings.minimumShareDifficulty} onChange={event=>changeSetting("minimumShareDifficulty",Number(event.target.value))}/></label>
     <label><span>Extra nonce size<small>Keep 2 for IceRiver compatibility.</small></span><input aria-label="Extra nonce size" type="number" min="1" max="4" value={settings.extranonceSize} onChange={event=>changeSetting("extranonceSize",Number(event.target.value))}/></label>
    </section><section className="panel settings-form"><div className="settings-heading"><div><h3>Automatic difficulty</h3><p>Keeps share submissions steady as miner speed changes.</p></div></div>
     <label className="toggle-row"><span>Variable difficulty<small>Recommended for stable ASIC mining.</small></span><input aria-label="Variable difficulty" type="checkbox" checked={settings.variableDifficulty} onChange={event=>changeSetting("variableDifficulty",event.target.checked)}/></label>
     <label><span>Target shares per minute<small>30 is the tested default.</small></span><input aria-label="Target shares per minute" type="number" min="1" max="120" value={settings.sharesPerMinute} onChange={event=>changeSetting("sharesPerMinute",Number(event.target.value))}/></label>
     <label className="toggle-row"><span>Power-of-two clamping<small>Required with variable difficulty for ASIC compatibility.</small></span><input aria-label="Power-of-two clamping" type="checkbox" checked={settings.powerOfTwoClamp} onChange={event=>changeSetting("powerOfTwoClamp",event.target.checked)}/></label>
    </section></section>
    <section className="panel protected-settings"><div><i>✓</i><span><strong>Umbrel node connection is protected</strong><small>{settingsModel.protected.nodeConnection}. It cannot be changed from this page.</small></span></div><div><i>✓</i><span><strong>No wallet or credentials</strong><small>This settings model does not read, accept, or store wallet information, miner passwords, or credentials.</small></span></div></section>
    {settingsIssues.length>0&&<section className="settings-errors" role="alert"><strong>Please check these settings:</strong><ul>{settingsIssues.map((item,index)=><li key={`${item.field}-${index}`}>{item.message}</li>)}</ul></section>}
    <section className="save-bar"><div><strong>Saving briefly interrupts miners</strong><span>The bridge restarts and checks itself. If it cannot start safely, the previous working settings are restored automatically.</span></div><button className="restart" disabled={settingsSaving||!manager?.bridge.managed} onClick={saveSettings}>{settingsSaving?"Saving and checking…":"Save and restart bridge"}</button></section>
   </>:<section className="panel settings-loading"><p>Settings are unavailable.</p><button onClick={loadSettings}>Try again</button></section>}
  </section>:<section className="panel empty"><b>≡</b><h2>{section}</h2><p>This module is scheduled for the next implementation milestone. The responsive application shell is ready.</p><button className="restart" onClick={()=>setSection("Overview")}>Return to overview</button></section>}
   <footer className="workspace-footer"><div className="developer-credit"><span>Developed by</span><a href="https://github.com/NoillioN-Labs" target="_blank" rel="noreferrer">NoillioN Labs</a></div>{section==="Overview"&&donationSupport?.enabled&&<div className="donation-area"><button className="donation-toggle" onClick={()=>setDonationsOpen(value=>!value)} aria-expanded={donationsOpen}>♡ Support development</button>{donationsOpen&&<section className="donation-popover" aria-label="Support development"><div><strong>Support Kaspa Stratum Manager</strong><button onClick={()=>setDonationsOpen(false)} aria-label="Close donation options">×</button></div><p>If this app helps your mining setup, you can optionally send Kaspa or Bitcoin. Select an address below and copy it manually.</p>{donationSupport.currencies.map(currency=><article key={currency.id}><span>{currency.label}</span><code title={currency.address}>{currency.address}</code></article>)}</section>}</div>}</footer>
  </section>
 </main>
}
