"use client";
import { useCallback, useEffect, useState } from "react";

const nav = ["Overview","Miners","Logs","Diagnostics","Settings"];
type ManagerStatus={profile:string;node:{endpoint:string;reachable:boolean;latency_ms:number;error:string|null};bridge:{managed:boolean;state:string;uptime_seconds:number;api_url:string;api:{reachable:boolean;error:string|null;status?:{kaspad_version?:string}}};checked_at:string};
type BridgeWorker={instance?:string;worker?:string;workerName?:string;name?:string;hashrate?:number;hashrateGhs?:number;shares?:number;acceptedShares?:number;status?:string};
type BridgeStats={activeWorkers?:number;totalShares?:number;networkHashrate?:number;bridgeUptime?:number;workers?:BridgeWorker[]};
const formatHashrate=(value?:number)=>value?value>=1e18?`${(value/1e18).toFixed(2)} EH/s`:value>=1e12?`${(value/1e12).toFixed(2)} TH/s`:`${(value/1e9).toFixed(2)} GH/s`:"—";
const workerHashrateGhs=(worker:BridgeWorker)=>worker.hashrateGhs??worker.hashrate??0;
const formatWorkerHashrate=(worker:BridgeWorker)=>formatHashrate(workerHashrateGhs(worker)*1e9);

export default function Home(){
 const [section,setSection]=useState("Overview"); const [manager,setManager]=useState<ManagerStatus|null>(null); const [stats,setStats]=useState<BridgeStats|null>(null); const [hashrateHistory,setHashrateHistory]=useState<number[]>([]); const [error,setError]=useState("");
 const managerBase=process.env.NEXT_PUBLIC_MANAGER_URL??"";
 const refresh=useCallback(async()=>{try{const statusResponse=await fetch(`${managerBase}/api/manager/status`,{cache:"no-store"});if(!statusResponse.ok)throw new Error(`Manager returned ${statusResponse.status}`);const status=await statusResponse.json();setManager(status);setError("");if(status.bridge.api.reachable){const statsResponse=await fetch(`${managerBase}/api/manager/stats`,{cache:"no-store"});if(statsResponse.ok){const liveStats:BridgeStats=await statsResponse.json();setStats(liveStats);const liveWorkers=Array.isArray(liveStats.workers)?liveStats.workers:[];const combinedGhs=liveWorkers.reduce((total,worker)=>total+workerHashrateGhs(worker),0);setHashrateHistory(previous=>[...previous.slice(-119),combinedGhs*1e9])}else setStats(null)}else setStats(null)}catch(reason){setStats(null);setError(reason instanceof Error?reason.message:"Manager unavailable")}},[managerBase]);
 useEffect(()=>{const initial=window.setTimeout(refresh,0);const timer=window.setInterval(refresh,5000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh]);
 const control=async(action:"start"|"stop"|"restart")=>{try{const response=await fetch(`${managerBase}/api/manager/bridge/${action}`,{method:"POST"});if(!response.ok)throw new Error((await response.json()).error||`Action failed (${response.status})`);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Action failed")}};
 const running=manager?.bridge.state==="running"||manager?.bridge.api.reachable===true;
 const hasLiveStats=manager?.bridge.api.reachable===true&&stats!==null;
 const workers=hasLiveStats&&Array.isArray(stats.workers)?stats.workers:[];
 const combinedMinerHashrate=workers.reduce((total,worker)=>total+workerHashrateGhs(worker),0)*1e9;
 const history=hasLiveStats?hashrateHistory:[];
 const historyMax=Math.max(1,...history);
 const metricSource=hasLiveStats?"Live bridge API":"Waiting for bridge";
 const metrics=[["Connected miners",hasLiveStats?(stats.activeWorkers??workers.length).toString():"—",metricSource],["Miner hashrate",hasLiveStats?formatHashrate(combinedMinerHashrate):"—",metricSource],["Accepted shares",hasLiveStats?stats.totalShares?.toLocaleString()??"0":"—",metricSource],["Node latency",manager?.node.reachable?`${manager.node.latency_ms} ms`:"—",manager?.node.endpoint??"Not checked"]];
 const healthSummary=manager?.node.reachable?(manager.bridge.api.reachable?"Healthy":"Ready for bridge"):"Attention";
 return <main className="shell">
  <aside><div className="brand">
   {/* SVG stays crisp at every Umbrel display density. */}
   {/* eslint-disable-next-line @next/next/no-img-element */}
   <img src="/kaspa-logo.svg" alt="Kaspa"/><small>Stratum Manager</small></div>
   <nav>{nav.map(x=><button key={x} className={x===section?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav>
   <div className="aside-status"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Rusty Kaspad connected":"Rusty Kaspad unavailable"}<small>{manager?.bridge.api.status?.kaspad_version??manager?.node.endpoint??"Checking connection…"}</small></div>
  </aside>
  <section className="workspace"><header><div><p>LOCAL MINING CONTROL</p><h1>{section}</h1></div><span className="node"><i className={manager?.node.reachable?"":"bad"}/>{manager?.node.reachable?"Node reachable":"Checking node"} <b>{manager?.node.latency_ms??"—"} ms</b></span></header>
  {error&&<div className="alert"><strong>Development connection:</strong> {error}. Start the manager on this computer to connect the dashboard.</div>}
  {section==="Overview"?<>
   <section className="hero"><div><span className={running?"running":"stopped"}>{running?"● Bridge running":"○ Bridge stopped"}</span><h2>{running?"Your miners can connect":"Waiting for the bridge"}<br/>to your own Kaspa node.</h2><p>{manager?.profile==="umbrel"?"Running locally inside Umbrel.":"Windows development profile connected across your LAN."}</p><code>stratum+tcp://umbrel.local:5555</code></div><div className="control"><div className="ring"><b>{running?new Date((manager?.bridge.uptime_seconds??stats?.bridgeUptime??0)*1000).toISOString().slice(11,19):"—"}</b><small>UPTIME</small></div><div><button disabled={!manager?.bridge.managed||!running} onClick={()=>control("stop")}>Stop</button><button disabled={!manager?.bridge.managed} className="restart" onClick={()=>control(running?"restart":"start")}>{running?"Restart":"Start"}</button></div></div></section>
   <section className="metrics">{metrics.map((m,i)=><article key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={i===0||i===2?"good":""}>{m[2]}</small></article>)}</section>
   <section className="grid"><article className="panel"><div className="panel-head"><div><h3>Miner hashrate</h3><p>Combined live miner performance</p></div><button disabled>Live session</button></div>{history.length>1?<div className="chart live-chart" aria-label="Live miner hashrate history"><div className="history-points">{history.map((value,index)=><i key={index} style={{height:`${Math.max(4,value/historyMax*100)}%`}} title={formatHashrate(value)}/>)}</div></div>:<div className="chart-empty"><b>Collecting live readings</b><span>The chart appears after two bridge updates.</span></div>}</article>
   <article className="panel"><div className="panel-head"><div><h3>System health</h3><p>Live management checks</p></div><em>{healthSummary}</em></div>{[["Rusty Kaspad RPC",manager?.node.endpoint??"Checking",manager?.node.reachable?"Active":"Unavailable",manager?.node.reachable],["Bridge API",manager?.bridge.api_url??"Checking",manager?.bridge.api.reachable?"Active":"Stopped",manager?.bridge.api.reachable],["Bridge supervisor",manager?.bridge.managed?"Managed":"Disabled in Windows profile",manager?.bridge.managed?"Active":"Expected",Boolean(manager)],["Runtime profile",manager?.profile??"Checking",manager?"Active":"Unavailable",Boolean(manager)]].map(x=><div className="health" key={String(x[0])}><i className={x[3]?"":"bad"}/><strong>{x[0]}<small>{x[1]}</small></strong><span className={x[2]==="Expected"?"safe":""}>{x[2]}</span></div>)}</article></section>
   <section className="panel miners"><div className="panel-head"><div><h3>Active miners</h3><p>Workers seen by the Stratum bridge</p></div><button onClick={()=>setSection("Miners")}>View all →</button></div>{workers.length?<div className="table"><table><thead><tr><th>Worker</th><th>Instance</th><th>Hashrate</th><th>Accepted shares</th><th>Status</th></tr></thead><tbody>{workers.map((worker,index)=>{const name=worker.worker??worker.workerName??worker.name??`Worker ${index+1}`;const status=worker.status??"Unknown";return <tr key={`${name}-${index}`}><td>{name}</td><td>{worker.instance??"—"}</td><td>{formatWorkerHashrate(worker)}</td><td>{(worker.acceptedShares??worker.shares??0).toLocaleString()}</td><td className={status.toLowerCase()}>{status}</td></tr>})}</tbody></table></div>:<div className="miners-empty"><b>No live miner data</b><span>{running?"Miner details will appear when a worker connects.":"Start the bridge to begin monitoring workers."}</span></div>}</section>
  </>:section==="Diagnostics"?<section className="panel diagnostics"><div className="panel-head"><div><h3>Connection diagnostics</h3><p>Windows development computer → Umbrel computer</p></div><button onClick={refresh}>Run checks</button></div><dl><div><dt>Development profile</dt><dd>{manager?.profile??"Manager unavailable"}</dd></div><div><dt>Rusty Kaspad RPC</dt><dd>{manager?.node.endpoint??"Not checked"} — {manager?.node.reachable?`reachable in ${manager.node.latency_ms} ms`:manager?.node.error??"unavailable"}</dd></div><div><dt>Rusty bridge API</dt><dd>{manager?.bridge.api_url??"Not checked"} — {manager?.bridge.api.reachable?"reachable":manager?.bridge.api.error??"unavailable"}</dd></div><div><dt>Process controls</dt><dd>{manager?.bridge.managed?"Enabled":"Disabled in Windows development profile"}</dd></div></dl></section>:<section className="panel empty"><b>{section==="Miners"?"◫":section==="Logs"?"≡":"⚙"}</b><h2>{section}</h2><p>This module is scheduled for the next implementation milestone. The responsive application shell is ready.</p><button className="restart" onClick={()=>setSection("Overview")}>Return to overview</button></section>}
  </section>
 </main>
}

