import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("renders Kaspa Stratum Manager metadata", async () => {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  const response = await worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>Kaspa Stratum Manager<\/title>/i);
  assert.match(html, /<link[^>]+rel="(?:shortcut )?icon"[^>]+href="\/favicon\.svg"/i);
  assert.match(html, /src="\/kaspa-logo\.svg"/i);
  assert.match(html, />Stratum Bridge Manager<\/small>/i);
  assert.doesNotMatch(html, /codex-preview/i);
});

test("dashboard source contains no representative mining records", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.doesNotMatch(source, /representative(?:Workers|Miners)|sample(?:Workers|Miners)/i);
  assert.match(source, /No live miner data/);
  assert.match(source, /Miner hashrate/);
  assert.match(source, /historyAverage/);
  assert.match(source, /Hashrate history range/);
  assert.match(source, /time-bucketed/);
  assert.match(source, /rangeLabels/);
  assert.match(source, /setInterval\(refresh,5000\)/);
  assert.match(source, /api\/manager\/metrics/);
  assert.match(source, /setInterval\(loadDashboardMetrics,5_000\)/);
  assert.match(source, /Recorded by manager/);
  assert.match(source, /Since manager records began/);
  assert.doesNotMatch(source, /setHashrateHistory/);
  assert.match(source, /combinedMinerHashrate/);
  assert.match(source, /workers\.slice\(0,5\)/);
  assert.match(source, /Showing up to 5 miners/);
  assert.match(source, /App version/);
  assert.match(source, /Bridge version/);
  assert.match(source, /Developed by/);
  assert.match(source, />NoillioN Labs</);
  assert.match(source, /Support development/);
  assert.match(source, /api\/manager\/support/);
  assert.match(source, /copy it manually/);
  assert.doesNotMatch(source, /Copy address|Open wallet|navigator\.clipboard/);
  assert.match(source, /system-health/);
  assert.match(source, /mobile-nav-toggle/);
  assert.match(source, /aria-controls="primary-navigation"/);
  assert.match(source, /aria-expanded=\{mobileMenuOpen\}/);
  assert.match(source, /setMobileMenuOpen\(false\)/);
  assert.match(source, /data-label="Accepted shares"/);
  assert.match(source, /Mining gateway is online/);
  assert.doesNotMatch(source, /\["Network hashrate"/);
  assert.match(source, /control\(running\?"restart":"start"\)/);
  assert.match(source, /running\?"Restart":"Start"/);
  assert.match(source, /Automatic is recommended for most miners/);
  assert.match(source, /Save and restart bridge/);
  assert.match(source, /Reset miner statistics/);
  assert.match(source, /Dark mode/);
  assert.match(source, /role="switch"/);
  assert.match(source, /kaspa-stratum-manager-theme/);
  assert.match(source, /saved in this browser/i);
  assert.match(source, /api\/manager\/statistics\/reset/);
  assert.match(source, /role="alertdialog"/);
  assert.match(source, /Delete all data/);
  assert.match(source, /cannot be undone/i);
  assert.match(source, /Saving briefly interrupts miners/);
  assert.match(source, /previous working settings are restored automatically/);
  assert.match(source, /Umbrel node connection is protected/);
  assert.match(source, /No wallet or credentials/);
  assert.match(source, /miners-page/);
  assert.match(source, /Miner directory/);
  assert.match(source, /Live status with locally retained performance windows/);
  assert.match(source, /Live data refreshes every 5 seconds/);
  assert.match(source, /Connect miners to your Umbrel/);
  assert.match(source, /Blocks found/);
  assert.match(source, /Last block/);
  assert.match(source, /blocks are confirmed by your node/i);
  assert.match(source, /confirms them blue/);
  assert.match(source, /worker\.blocks/);
  assert.match(source, /miningOutlook\.recentBlocks/);
  assert.match(source, /api\/manager\/history/);
  assert.match(source, /7-day solo mining outlook/);
  assert.match(source, /chance of at least one block/i);
  assert.match(source, /Estimated average wait/);
  assert.match(source, /Average network hashrate/);
  assert.match(source, /Network blocks observed/);
  assert.match(source, /Per-miner 7-day outlook/);
  assert.match(source, /Hashrate performance/);
  assert.match(source, /1-hour average/);
  assert.match(source, /6-hour average/);
  assert.match(source, /24-hour average/);
  assert.match(source, /Last accepted share/);
  assert.match(source, /Share health/);
  assert.match(source, /Actual versus expected/);
  assert.match(source, /Observed block luck/);
  assert.match(source, /Current round effort/);
  assert.match(source, /Recent confirmed blocks/);
  assert.match(source, /Confirmed blue/);
  assert.match(source, /More than 100% is normal/);
  assert.match(source, /Forecasts use changing network conditions/i);
  assert.match(source, /not promises/i);
  assert.match(source, /Live application logs/);
  assert.match(source, /api\/manager\/logs\?limit=200/);
  assert.match(source, /Newest messages appear first/);
  assert.match(source, /Kept in memory only/);
  assert.match(source, /aria-label="Search logs"/);
  assert.match(source, /Everything is ready for mining/);
  assert.match(source, /Live service checks/);
  assert.match(source, /Stratum listener/);
  assert.match(source, /TCP port 5555/);
  assert.match(source, /Runtime details/);
  assert.match(source, /If something is not working/);
  assert.match(source, /aria-label="Stratum port"[^>]*disabled readOnly/);
  assert.match(source, /window\.location\.hostname/);
  assert.doesNotMatch(source, /umbrel\.local/i);
});

test("dashboard styles provide a readable iPhone layout", async () => {
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(styles, /@media \(max-width:700px\)/);
  assert.match(styles, /\.shell nav\.mobile-open\{display:grid/);
  assert.match(styles, /\.mobile-nav-toggle\{display:grid/);
  assert.match(styles, /\.history-points i:nth-last-child\(-n\+60\)/);
  assert.match(styles, /\.chart-range button/);
  assert.match(styles, /\.performance-window-grid/);
  assert.match(styles, /\.share-activity span,\.outlook-inputs span\{display:flex;align-items:baseline;justify-content:flex-start/);
  assert.match(styles, /\.confirm-backdrop/);
  assert.match(styles, /:root\[data-theme="dark"\]/);
  assert.match(styles, /\.theme-control input:checked\+i/);
  assert.match(styles, /:root\[data-theme="dark"\] \.logs-summary article/);
  assert.match(styles, /:root\[data-theme="dark"\] \.logs-intro>button/);
  assert.match(styles, /:root\[data-theme="dark"\] \.diagnostics-banner button/);
  assert.match(styles, /:root\[data-theme="dark"\] \.workspace-footer/);
  assert.match(styles, /:root\[data-theme="dark"\] \.donation-popover/);
  assert.match(styles, /\.recent-blocks table,\.recent-blocks tbody/);
  assert.match(styles, /\.miners table,\.miners tbody,\.miners tr,\.miners td\{display:block/);
  assert.match(styles, /\.system-health \.health strong\{font-size:13px/);
  assert.match(styles, /\.log-search input\{min-height:44px;font-size:16px/);
  assert.match(styles, /@media \(max-width:380px\)/);
});

